name: Omada controller proxy
version: "1.2.6"
slug: omada_controller_proxy
description: Full Home Assistant Ingress reverse proxy for an Omada Controller
url: https://github.com/JasonPeng99/home-assistant-omada-controller-proxy
arch:
  - amd64
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_admin: true
panel_icon: mdi:lan
panel_title: Omada Controller
homeassistant_api: false
options:
  controller_ip: ""
  controller_port: 8043
  username: ""
  password: ""
  verify_ssl: false
schema:
  controller_ip: str
  controller_port: port
  username: str
  password: password
  verify_ssl: bool
